if(!this.JSON)this.JSON={};
(function(){function a(f){return f<10?"0"+f:f}function b(f){m.lastIndex=0;return m.test(f)?'"'+f.replace(m,function(j){var d=r[j];return typeof d==="string"?d:"\\u"+("0000"+j.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+f+'"'}function h(f,j){var d,g,k,n,l=e,i,c=j[f];if(c&&typeof c==="object"&&typeof c.toJSON==="function")c=c.toJSON(f);if(typeof o==="function")c=o.call(j,f,c);switch(typeof c){case "string":return b(c);case "number":return isFinite(c)?String(c):"null";case "boolean":case "null":return String(c);
case "object":if(!c)return"null";e+=q;i=[];if(Object.prototype.toString.apply(c)==="[object Array]"){n=c.length;for(d=0;d<n;d+=1)i[d]=h(d,c)||"null";k=i.length===0?"[]":e?"[\n"+e+i.join(",\n"+e)+"\n"+l+"]":"["+i.join(",")+"]";e=l;return k}if(o&&typeof o==="object"){n=o.length;for(d=0;d<n;d+=1){g=o[d];if(typeof g==="string")if(k=h(g,c))i.push(b(g)+(e?": ":":")+k)}}else for(g in c)if(Object.hasOwnProperty.call(c,g))if(k=h(g,c))i.push(b(g)+(e?": ":":")+k);k=i.length===0?"{}":e?"{\n"+e+i.join(",\n"+e)+
"\n"+l+"}":"{"+i.join(",")+"}";e=l;return k}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var p=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
m=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,q,r={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},o;if(typeof JSON.stringify!=="function")JSON.stringify=function(f,j,d){var g;q=e="";if(typeof d==="number")for(g=0;g<d;g+=1)q+=" ";else if(typeof d==="string")q=d;if((o=j)&&typeof j!=="function"&&(typeof j!=="object"||typeof j.length!=="number"))throw Error("JSON.stringify");return h("",
{"":f})};if(typeof JSON.parse!=="function")JSON.parse=function(f,j){function d(k,n){var l,i,c=k[n];if(c&&typeof c==="object")for(l in c)if(Object.hasOwnProperty.call(c,l)){i=d(c,l);if(i!==undefined)c[l]=i;else delete c[l]}return j.call(k,n,c)}var g;p.lastIndex=0;if(p.test(f))f=f.replace(p,function(k){return"\\u"+("0000"+k.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(f.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){g=eval("("+f+")");return typeof j==="function"?d({"":g},""):g}throw new SyntaxError("JSON.parse");}})();$(document).ready(function(){setTimeout("msgflow_pull()",2E3)});function msgflow_pull(){$.getJSON(msgflow_base_url+"/extern.php?action=msgflow&from="+msgflow_timestamp,msgflow_callback)}function msgflow_beep(){var a=document.createElement("audio");if(typeof a.load=="function"){a.setAttribute("src",msgflow_base_url+"/extensions/msgflow/sound/beep_mult.ogg");a.load();a.play()}}
function msgflow_callback(a){var b=msgflow_timestamp;$(a.updates).each(function(){if(this.posted>msgflow_timestamp){b=this.posted;if(msgflow_forum_page=="index")msgflow_index(this);else if(msgflow_forum_page=="viewforum")msgflow_forum_id==this.forum_id&&msgflow_viewforum(this);else msgflow_forum_page=="searchtopics"&&msgflow_forum_action=="show_recent"&&msgflow_showrecent(this)}});if(msgflow_timestamp<b){msgflow_timestamp=b;msgflow_beep();if(!msgflow_document_title)msgflow_document_title=document.title;
document.title="New posts! - "+msgflow_document_title}a.status=="success"&&msgflow_pull()}
function msgflow_index(a){var b=$("#forum"+a.forum_id);$(b).addClass("new").children("span.icon").addClass("new");$(b).find("li.info-topics > strong").text(a.num_topics);$(b).find("li.info-posts > strong").text(a.num_posts);$(b).find("li.info-lastpost > strong").html('<a href="'+a.post_url+'">'+a.date+"</a>");$(b).find("li.info-lastpost > cite").length==0&&$("<cite/>").insertAfter($(b).find("li.info-lastpost > strong"));$(b).find("li.info-lastpost > cite").text("by "+a.poster);if($(b).children("div.item-subject").find("small").length==
0){var h=$("<small/>");$(h).html(' ( <a title="This forum contain posts made since your last visit." href="'+a.forum_newpost_url+'">New posts</a> )').insertAfter($(b).children("div.item-subject").find("a"))}}
function msgflow_item_nav(a,b,h,p){var m=$("<div/>").html("( ");if(h>1){$(m).append("<span>Pages&#160;</span>");for(var e=1;e<h+1;e++)e==1?$(m).append($("<a/>").attr("href",b).text(e).addClass("first-item")).append("&#160;"):$(m).append($("<a/>").attr("href",b+"&p="+e).text(e)).append("&#160;")}$(m).append('<em class="item-newposts"> <a href="'+p+'">New posts</a></em> )');$(a).html($(m).html())}
function msgflow_viewforum(a){if($("#topic"+a.topic_id).length>0){var b=$("#topic"+a.topic_id);$(b).addClass("new").children("span.icon").addClass("new");$(b).find("li.info-replies > strong").text(a.num_replies);$(b).find("li.info-views > strong").text(a.num_views);$(b).find("li.info-lastpost > strong").html('<a href="'+a.post_url+'">'+a.date+"</a>");$(b).find("li.info-lastpost > cite").text("by "+a.poster);$(b).children("div.item-subject").find("span.item-nav").length==0&&$("<span/>").addClass("item-nav").insertAfter($(b).find("span.item-starter").append(" "));
msgflow_item_nav($(b).children("div.item-subject").find("span.item-nav"),a.topic_url,a.topic_pages,a.topic_newpost_url);if($(b).hasClass("sticky")){$("div.main-item:first").removeClass("main-first-item");$(b).addClass("main-first-item").prependTo($("div.main-content"))}else{a=$("div.main-item").not(".sticky").filter(":first");if($(a).length>0&&$(a)[0]!=$(b)[0]){$(a).removeClass("main-first-item");$(b).insertBefore($(a))}$("div.main-item:first").addClass("main-first-item")}}else{b=$("<div/>").attr("id",
"topic"+a.topic_id).addClass("main-item normal new").append($("<span/>").addClass("icon normal new").html("<!-- --\>")).append($("<div/>").addClass("item-subject").append($("<h3/>").addClass("hn").append($("<span/>").addClass("item-num")).append($("<a/>").attr("href",a.topic_url).text(a.subject))).append($("<p/>").append($("<span/>").addClass("item-starter").text("by ").append($("<cite/>").text(a.creator))).append("&#160;").append($("<span/>").addClass("item-nav")))).append($("<ul/>").addClass("item-info").append($("<li/>").addClass("info-replies").append($("<strong/>").text(a.num_replies)).append($("<span/>").addClass("label").text(" reply"))).append($("<li/>").addClass("info-views").append($("<strong/>").text(a.num_views)).append($("<span/>").addClass("label").text(" views"))).append($("<li/>").addClass("info-lastpost").append($("<span/>").addClass("label").text("Last post ")).append($("<strong/>").append($("<a/>").attr("href",
a.post_url).text(a.date))).append($("<cite/>").text("by ").append(a.poster))));msgflow_item_nav($(b).children("div.item-subject").find("span.item-nav"),a.topic_url,a.topic_pages,a.topic_newpost_url);$("div.main-item").length>msgflow_disp_topics&&$("div.main-item:last").remove();a=$("div.main-item").not(".sticky").filter(":first");if($(a).length>0){$(a).removeClass("main-first-item");$(b).insertBefore($(a))}else{a=$("div.main-item:last");$(b).insertAfter($(a))}$("div.main-item:first").addClass("main-first-item")}$("div.main-item").each(function(h){$(this).removeClass("even").removeClass("odd");
h%2==0?$(this).addClass("odd"):$(this).addClass("even");$(this).find("span.item-num").text(h+1)})}
function msgflow_showrecent(a){if($("#topic"+a.topic_id).length>0){var b=$("#topic"+a.topic_id);$(b).addClass("new").children("span.icon").addClass("new");$(b).find("li.info-replies > strong").text(a.num_replies);$(b).find("li.info-lastpost > strong").html('<a href="'+a.post_url+'">'+a.date+"</a>");$(b).find("li.info-lastpost > cite").text("by "+a.poster);$(b).children("div.item-subject").find("span.item-nav").length==0&&$("<span/>").addClass("item-nav").insertAfter($(b).find("span.item-starter").append(" "));
msgflow_item_nav($(b).children("div.item-subject").find("span.item-nav"),a.topic_url,a.topic_pages,a.topic_newpost_url);$("div.main-item:first").removeClass("main-first-item")}else{b=$("<div/>").attr("id","topic"+a.topic_id).addClass("main-item normal new").append($("<span/>").addClass("icon normal new").html("<!-- --\>")).append($("<div/>").addClass("item-subject").append($("<h3/>").addClass("hn").append($("<span/>").addClass("item-num")).append($("<a/>").attr("href",a.topic_url).text(a.subject))).append($("<p/>").append($("<span/>").addClass("item-starter").text("by ").append($("<cite/>").text(a.creator))).append("&#160;").append($("<span/>").addClass("item-nav")))).append($("<ul/>").addClass("item-info").append($("<li/>").addClass("info-forum").append($("<span/>").addClass("label").text("Posted in")).append($("<a/>").attr("href",
a.forum_url).text(a.forum_name))).append($("<li/>").addClass("info-replies").append($("<strong/>").text(a.num_replies)).append($("<span/>").addClass("label").text(" reply"))).append($("<li/>").addClass("info-lastpost").append($("<span/>").addClass("label").text("Last post ")).append($("<strong/>").append($("<a/>").attr("href",a.post_url).text(a.date))).append($("<cite/>").text("by ").append(a.poster))));$("div.main-item").length>msgflow_disp_topics&&$("div.main-item:last").remove();$("div.main-item:first").removeClass("main-first-item");
msgflow_item_nav($(b).children("div.item-subject").find("span.item-nav"),a.topic_url,a.topic_pages,a.topic_newpost_url)}$(b).addClass("main-first-item").prependTo($("div.main-content"));$("div.main-item").each(function(h){$(this).removeClass("even").removeClass("odd");h%2==0?$(this).addClass("odd"):$(this).addClass("even");$(this).find("span.item-num").text(h+1)})};
