if(!this.JSON)this.JSON={};
(function(){function a(e){return e<10?"0"+e:e}function b(e){q.lastIndex=0;return q.test(e)?'"'+e.replace(q,function(h){var d=r[h];return typeof d==="string"?d:"\\u"+("0000"+h.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+e+'"'}function l(e,h){var d,f,i,m,k=j,g,c=h[e];if(c&&typeof c==="object"&&typeof c.toJSON==="function")c=c.toJSON(e);if(typeof n==="function")c=n.call(h,e,c);switch(typeof c){case "string":return b(c);case "number":return isFinite(c)?String(c):"null";case "boolean":case "null":return String(c);
case "object":if(!c)return"null";j+=p;g=[];if(Object.prototype.toString.apply(c)==="[object Array]"){m=c.length;for(d=0;d<m;d+=1)g[d]=l(d,c)||"null";i=g.length===0?"[]":j?"[\n"+j+g.join(",\n"+j)+"\n"+k+"]":"["+g.join(",")+"]";j=k;return i}if(n&&typeof n==="object"){m=n.length;for(d=0;d<m;d+=1){f=n[d];if(typeof f==="string")if(i=l(f,c))g.push(b(f)+(j?": ":":")+i)}}else for(f in c)if(Object.hasOwnProperty.call(c,f))if(i=l(f,c))g.push(b(f)+(j?": ":":")+i);i=g.length===0?"{}":j?"{\n"+j+g.join(",\n"+j)+
"\n"+k+"}":"{"+g.join(",")+"}";j=k;return i}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var o=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
q=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,j,p,r={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},n;if(typeof JSON.stringify!=="function")JSON.stringify=function(e,h,d){var f;p=j="";if(typeof d==="number")for(f=0;f<d;f+=1)p+=" ";else if(typeof d==="string")p=d;if((n=h)&&typeof h!=="function"&&(typeof h!=="object"||typeof h.length!=="number"))throw Error("JSON.stringify");return l("",
{"":e})};if(typeof JSON.parse!=="function")JSON.parse=function(e,h){function d(i,m){var k,g,c=i[m];if(c&&typeof c==="object")for(k in c)if(Object.hasOwnProperty.call(c,k)){g=d(c,k);if(g!==undefined)c[k]=g;else delete c[k]}return h.call(i,m,c)}var f;o.lastIndex=0;if(o.test(e))e=e.replace(o,function(i){return"\\u"+("0000"+i.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(e.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){f=eval("("+e+")");return typeof h==="function"?d({"":f},""):f}throw new SyntaxError("JSON.parse");}})();$(document).ready(function(){setTimeout("msgflow_pull()",2E3)});function msgflow_pull(){$.getJSON(msgflow_base_url+"/extern.php?action=msgflow&from="+msgflow_timestamp,msgflow_callback)}function msgflow_beep(){var a=document.createElement("audio");if(typeof a.load=="function"){a.setAttribute("src",msgflow_base_url+"/extensions/msgflow/sound/beep_mult.ogg");a.load();a.play()}}
function msgflow_callback(a){var b=msgflow_timestamp;$(a.updates).each(function(){if(this.posted>msgflow_timestamp){b=this.posted;if(msgflow_forum_page=="index")msgflow_index(this);else msgflow_forum_page=="viewforum"&&msgflow_forum_id==this.forum_id&&msgflow_viewforum(this)}});if(msgflow_timestamp<b){msgflow_timestamp=b;msgflow_beep();if(!msgflow_document_title)msgflow_document_title=document.title;document.title="New posts! - "+msgflow_document_title}a.status=="success"&&msgflow_pull()}
function msgflow_index(a){var b=$("#forum"+a.forum_id);$(b).addClass("new").children("span.icon").addClass("new");$(b).find("li.info-topics > strong").text(a.num_topics);$(b).find("li.info-posts > strong").text(a.num_posts);$(b).find("li.info-lastpost > strong").html('<a href="'+a.post_url+'">'+a.date+"</a>");$(b).find("li.info-lastpost > cite").length==0&&$("<cite/>").insertAfter($(b).find("li.info-lastpost > strong"));$(b).find("li.info-lastpost > cite").text("by "+a.poster);if($(b).children("div.item-subject").find("small").length==
0){var l=$("<small/>");$(l).html(' ( <a title="This forum contain posts made since your last visit." href="'+a.forum_newpost_url+'">New posts</a> )').insertAfter($(b).children("div.item-subject").find("a"))}}
function msgflow_viewforum(a){if($("#topic"+a.topic_id).length>0){var b=$("#topic"+a.topic_id);$(b).addClass("new").children("span.icon").addClass("new");$(b).find("li.info-replies > strong").text(a.num_replies);$(b).find("li.info-views > strong").text(a.num_views);$(b).find("li.info-lastpost > strong").html('<a href="'+a.post_url+'">'+a.date+"</a>");$(b).find("li.info-lastpost > cite").text("by "+a.poster);if($(b).children("div.item-subject").find("span.item-nav").length==0){var l=$("<span/>");$(l).addClass("item-nav").html(' ( <em class="item-newposts"> <a href="'+
a.topic_newpost_url+'">New posts</a></em> )').insertAfter($(b).find("span.item-starter"))}if($(b).hasClass("sticky")){$("div.main-item:first").removeClass("main-first-item");$(b).addClass("main-first-item").prependTo($("div.main-content"))}else{a=$("div.main-item").not(".sticky").filter(":first");if($(a).length>0&&$(a)[0]!=$(b)[0]){$(a).removeClass("main-first-item");$(b).insertBefore($(a))}$("div.main-item:first").addClass("main-first-item")}}else{b=$("<div/>").attr("id","topic"+a.topic_id).addClass("main-item normal new").append($("<span/>").addClass("icon normal new").html("<!-- --\>")).append($("<div/>").addClass("item-subject").append($("<h3/>").addClass("hn").append($("<span/>").addClass("item-num")).append($("<a/>").attr("href",
a.topic_url).text(a.subject))).append($("<p/>").append($("<span/>").addClass("item-starter").text("by ").append($("<cite/>").text(a.creator))).append($("<span/>").addClass("item-nav").text(" ( ").append($("<em/>").addClass("item-newposts").append($("<a/>").attr("href",a.topic_newpost_url).text("New posts"))).append(" )")))).append($("<ul/>").addClass("item-info").append($("<li/>").addClass("info-replies").append($("<strong/>").text(a.num_replies)).append($("<span/>").addClass("label").text(" reply"))).append($("<li/>").addClass("info-views").append($("<strong/>").text(a.num_views)).append($("<span/>").addClass("label").text(" views"))).append($("<li/>").addClass("info-lastpost").append($("<span/>").addClass("label").text("Last post ")).append($("<strong/>").append($("<a/>").attr("href",
a.post_url).text(a.date))).append($("<cite/>").text("by ").append(a.poster))));$("div.main-item").length>msgflow_disp_topics&&$("div.main-item:last").remove();a=$("div.main-item").not(".sticky").filter(":first");if($(a).length>0){$(a).removeClass("main-first-item");$(b).insertBefore($(a))}else{a=$("div.main-item:last");$(b).insertAfter($(a))}$("div.main-item:first").addClass("main-first-item")}$("div.main-item").each(function(o){$(this).removeClass("even").removeClass("odd");o%2==0?$(this).addClass("odd"):
$(this).addClass("even");$(this).find("span.item-num").text(o+1)})};
